//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Media;

namespace PoshCode.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Colors : ApplicationSettingsBase {
        
        private static Colors defaultInstance = ((Colors)(Synchronized(new Colors())));
        
        public static Colors Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("White")]
        public ConsoleColor DefaultForeground {
            get {
                return ((ConsoleColor)(this["DefaultForeground"]));
            }
            set {
                this["DefaultForeground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Black")]
        public ConsoleColor DefaultBackground {
            get {
                return ((ConsoleColor)(this["DefaultBackground"]));
            }
            set {
                this["DefaultBackground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF000000")]
        public Color Black {
            get {
                return ((Color)(this["Black"]));
            }
            set {
                this["Black"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF0066FF")]
        public Color Blue {
            get {
                return ((Color)(this["Blue"]));
            }
            set {
                this["Blue"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF99CCFF")]
        public Color Cyan {
            get {
                return ((Color)(this["Cyan"]));
            }
            set {
                this["Cyan"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF003399")]
        public Color DarkBlue {
            get {
                return ((Color)(this["DarkBlue"]));
            }
            set {
                this["DarkBlue"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF006699")]
        public Color DarkCyan {
            get {
                return ((Color)(this["DarkCyan"]));
            }
            set {
                this["DarkCyan"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF666666")]
        public Color DarkGray {
            get {
                return ((Color)(this["DarkGray"]));
            }
            set {
                this["DarkGray"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF006633")]
        public Color DarkGreen {
            get {
                return ((Color)(this["DarkGreen"]));
            }
            set {
                this["DarkGreen"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF800080")]
        public Color DarkMagenta {
            get {
                return ((Color)(this["DarkMagenta"]));
            }
            set {
                this["DarkMagenta"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF800000")]
        public Color DarkRed {
            get {
                return ((Color)(this["DarkRed"]));
            }
            set {
                this["DarkRed"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFF9900")]
        public Color DarkYellow {
            get {
                return ((Color)(this["DarkYellow"]));
            }
            set {
                this["DarkYellow"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFCCCCCC")]
        public Color Gray {
            get {
                return ((Color)(this["Gray"]));
            }
            set {
                this["Gray"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF66CC00")]
        public Color Green {
            get {
                return ((Color)(this["Green"]));
            }
            set {
                this["Green"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFF1493")]
        public Color Magenta {
            get {
                return ((Color)(this["Magenta"]));
            }
            set {
                this["Magenta"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFF0000")]
        public Color Red {
            get {
                return ((Color)(this["Red"]));
            }
            set {
                this["Red"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color White {
            get {
                return ((Color)(this["White"]));
            }
            set {
                this["White"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFD700")]
        public Color Yellow {
            get {
                return ((Color)(this["Yellow"]));
            }
            set {
                this["Yellow"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#00FFFFFF")]
        public Color DebugBackground {
            get {
                return ((Color)(this["DebugBackground"]));
            }
            set {
                this["DebugBackground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFA900")]
        public Color DebugForeground {
            get {
                return ((Color)(this["DebugForeground"]));
            }
            set {
                this["DebugForeground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#00FFFFFF")]
        public Color ErrorBackground {
            get {
                return ((Color)(this["ErrorBackground"]));
            }
            set {
                this["ErrorBackground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFF0056")]
        public Color ErrorForeground {
            get {
                return ((Color)(this["ErrorForeground"]));
            }
            set {
                this["ErrorForeground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#00FFFFFF")]
        public Color VerboseBackground {
            get {
                return ((Color)(this["VerboseBackground"]));
            }
            set {
                this["VerboseBackground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF93FF29")]
        public Color VerboseForeground {
            get {
                return ((Color)(this["VerboseForeground"]));
            }
            set {
                this["VerboseForeground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#00FFFFFF")]
        public Color WarningBackground {
            get {
                return ((Color)(this["WarningBackground"]));
            }
            set {
                this["WarningBackground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFF7AA7")]
        public Color WarningForeground {
            get {
                return ((Color)(this["WarningForeground"]));
            }
            set {
                this["WarningForeground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFFFFFF")]
        public Color NativeOutputForeground {
            get {
                return ((Color)(this["NativeOutputForeground"]));
            }
            set {
                this["NativeOutputForeground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#22FFFFFF")]
        public Color NativeOutputBackground {
            get {
                return ((Color)(this["NativeOutputBackground"]));
            }
            set {
                this["NativeOutputBackground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFF2771")]
        public Color NativeErrorForeground {
            get {
                return ((Color)(this["NativeErrorForeground"]));
            }
            set {
                this["NativeErrorForeground"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#22FFFFFF")]
        public Color NativeErrorBackground {
            get {
                return ((Color)(this["NativeErrorBackground"]));
            }
            set {
                this["NativeErrorBackground"] = value;
            }
        }
    }
}
