//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoshConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Colors : global::System.Configuration.ApplicationSettingsBase {
        
        private static Colors defaultInstance = ((Colors)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Colors())));
        
        public static Colors Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.ConsoleColor DefaultForeground {
            get {
                return ((global::System.ConsoleColor)(this["DefaultForeground"]));
            }
            set {
                this["DefaultForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.ConsoleColor DefaultBackground {
            get {
                return ((global::System.ConsoleColor)(this["DefaultBackground"]));
            }
            set {
                this["DefaultBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color Black {
            get {
                return ((global::System.Windows.Media.Color)(this["Black"]));
            }
            set {
                this["Black"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0066FF")]
        public global::System.Windows.Media.Color Blue {
            get {
                return ((global::System.Windows.Media.Color)(this["Blue"]));
            }
            set {
                this["Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF99CCFF")]
        public global::System.Windows.Media.Color Cyan {
            get {
                return ((global::System.Windows.Media.Color)(this["Cyan"]));
            }
            set {
                this["Cyan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF003399")]
        public global::System.Windows.Media.Color DarkBlue {
            get {
                return ((global::System.Windows.Media.Color)(this["DarkBlue"]));
            }
            set {
                this["DarkBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF006699")]
        public global::System.Windows.Media.Color DarkCyan {
            get {
                return ((global::System.Windows.Media.Color)(this["DarkCyan"]));
            }
            set {
                this["DarkCyan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF666666")]
        public global::System.Windows.Media.Color DarkGray {
            get {
                return ((global::System.Windows.Media.Color)(this["DarkGray"]));
            }
            set {
                this["DarkGray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF006633")]
        public global::System.Windows.Media.Color DarkGreen {
            get {
                return ((global::System.Windows.Media.Color)(this["DarkGreen"]));
            }
            set {
                this["DarkGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF800080")]
        public global::System.Windows.Media.Color DarkMagenta {
            get {
                return ((global::System.Windows.Media.Color)(this["DarkMagenta"]));
            }
            set {
                this["DarkMagenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF800000")]
        public global::System.Windows.Media.Color DarkRed {
            get {
                return ((global::System.Windows.Media.Color)(this["DarkRed"]));
            }
            set {
                this["DarkRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF9900")]
        public global::System.Windows.Media.Color DarkYellow {
            get {
                return ((global::System.Windows.Media.Color)(this["DarkYellow"]));
            }
            set {
                this["DarkYellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public global::System.Windows.Media.Color Gray {
            get {
                return ((global::System.Windows.Media.Color)(this["Gray"]));
            }
            set {
                this["Gray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF66CC00")]
        public global::System.Windows.Media.Color Green {
            get {
                return ((global::System.Windows.Media.Color)(this["Green"]));
            }
            set {
                this["Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF1493")]
        public global::System.Windows.Media.Color Magenta {
            get {
                return ((global::System.Windows.Media.Color)(this["Magenta"]));
            }
            set {
                this["Magenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color Red {
            get {
                return ((global::System.Windows.Media.Color)(this["Red"]));
            }
            set {
                this["Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color White {
            get {
                return ((global::System.Windows.Media.Color)(this["White"]));
            }
            set {
                this["White"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFD700")]
        public global::System.Windows.Media.Color Yellow {
            get {
                return ((global::System.Windows.Media.Color)(this["Yellow"]));
            }
            set {
                this["Yellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public global::System.Windows.Media.Color DebugBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["DebugBackground"]));
            }
            set {
                this["DebugBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFA900")]
        public global::System.Windows.Media.Color DebugForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["DebugForeground"]));
            }
            set {
                this["DebugForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public global::System.Windows.Media.Color ErrorBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["ErrorBackground"]));
            }
            set {
                this["ErrorBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0056")]
        public global::System.Windows.Media.Color ErrorForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["ErrorForeground"]));
            }
            set {
                this["ErrorForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public global::System.Windows.Media.Color VerboseBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["VerboseBackground"]));
            }
            set {
                this["VerboseBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF93FF29")]
        public global::System.Windows.Media.Color VerboseForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["VerboseForeground"]));
            }
            set {
                this["VerboseForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#00FFFFFF")]
        public global::System.Windows.Media.Color WarningBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["WarningBackground"]));
            }
            set {
                this["WarningBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF7AA7")]
        public global::System.Windows.Media.Color WarningForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["WarningForeground"]));
            }
            set {
                this["WarningForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color NativeOutputForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["NativeOutputForeground"]));
            }
            set {
                this["NativeOutputForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#22FFFFFF")]
        public global::System.Windows.Media.Color NativeOutputBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["NativeOutputBackground"]));
            }
            set {
                this["NativeOutputBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF2771")]
        public global::System.Windows.Media.Color NativeErrorForeground {
            get {
                return ((global::System.Windows.Media.Color)(this["NativeErrorForeground"]));
            }
            set {
                this["NativeErrorForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#22FFFFFF")]
        public global::System.Windows.Media.Color NativeErrorBackground {
            get {
                return ((global::System.Windows.Media.Color)(this["NativeErrorBackground"]));
            }
            set {
                this["NativeErrorBackground"] = value;
            }
        }
    }
}
