//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Huddled.PoshConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "8.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF000000")]
        public global::System.Windows.Media.Color ConsoleBlack {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleBlack"]));
            }
            set {
                this["ConsoleBlack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0066FF")]
        public global::System.Windows.Media.Color ConsoleBlue {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleBlue"]));
            }
            set {
                this["ConsoleBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF99CCFF")]
        public global::System.Windows.Media.Color ConsoleCyan {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleCyan"]));
            }
            set {
                this["ConsoleCyan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF003399")]
        public global::System.Windows.Media.Color ConsoleDarkBlue {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleDarkBlue"]));
            }
            set {
                this["ConsoleDarkBlue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF006699")]
        public global::System.Windows.Media.Color ConsoleDarkCyan {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleDarkCyan"]));
            }
            set {
                this["ConsoleDarkCyan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF666666")]
        public global::System.Windows.Media.Color ConsoleDarkGray {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleDarkGray"]));
            }
            set {
                this["ConsoleDarkGray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF006633")]
        public global::System.Windows.Media.Color ConsoleDarkGreen {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleDarkGreen"]));
            }
            set {
                this["ConsoleDarkGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF800080")]
        public global::System.Windows.Media.Color ConsoleDarkMagenta {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleDarkMagenta"]));
            }
            set {
                this["ConsoleDarkMagenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF800000")]
        public global::System.Windows.Media.Color ConsoleDarkRed {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleDarkRed"]));
            }
            set {
                this["ConsoleDarkRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF9900")]
        public global::System.Windows.Media.Color ConsoleDarkYellow {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleDarkYellow"]));
            }
            set {
                this["ConsoleDarkYellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFCCCCCC")]
        public global::System.Windows.Media.Color ConsoleGray {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleGray"]));
            }
            set {
                this["ConsoleGray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF66CC00")]
        public global::System.Windows.Media.Color ConsoleGreen {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleGreen"]));
            }
            set {
                this["ConsoleGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF1493")]
        public global::System.Windows.Media.Color ConsoleMagenta {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleMagenta"]));
            }
            set {
                this["ConsoleMagenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF0000")]
        public global::System.Windows.Media.Color ConsoleRed {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleRed"]));
            }
            set {
                this["ConsoleRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFFFFF")]
        public global::System.Windows.Media.Color ConsoleWhite {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleWhite"]));
            }
            set {
                this["ConsoleWhite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFD700")]
        public global::System.Windows.Media.Color ConsoleYellow {
            get {
                return ((global::System.Windows.Media.Color)(this["ConsoleYellow"]));
            }
            set {
                this["ConsoleYellow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CopyOnMouseSelect {
            get {
                return ((bool)(this["CopyOnMouseSelect"]));
            }
            set {
                this["CopyOnMouseSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Huddled.Hotkeys.Hotkey FocusKey {
            get {
                return ((global::Huddled.Hotkeys.Hotkey)(this["FocusKey"]));
            }
            set {
                this["FocusKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.ConsoleColor ConsoleDefaultForeground {
            get {
                return ((global::System.ConsoleColor)(this["ConsoleDefaultForeground"]));
            }
            set {
                this["ConsoleDefaultForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.ConsoleColor ConsoleDefaultBackground {
            get {
                return ((global::System.ConsoleColor)(this["ConsoleDefaultBackground"]));
            }
            set {
                this["ConsoleDefaultBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::System.Windows.WindowStyle WindowStyle {
            get {
                return ((global::System.Windows.WindowStyle)(this["WindowStyle"]));
            }
            set {
                this["WindowStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowInTaskbar {
            get {
                return ((bool)(this["ShowInTaskbar"]));
            }
            set {
                this["ShowInTaskbar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double WindowHeight {
            get {
                return ((double)(this["WindowHeight"]));
            }
            set {
                this["WindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double WindowLeft {
            get {
                return ((double)(this["WindowLeft"]));
            }
            set {
                this["WindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double WindowWidth {
            get {
                return ((double)(this["WindowWidth"]));
            }
            set {
                this["WindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double WindowTop {
            get {
                return ((double)(this["WindowTop"]));
            }
            set {
                this["WindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Animate {
            get {
                return ((bool)(this["Animate"]));
            }
            set {
                this["Animate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SnapToScreenEdge {
            get {
                return ((bool)(this["SnapToScreenEdge"]));
            }
            set {
                this["SnapToScreenEdge"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double SnapDistance {
            get {
                return ((double)(this["SnapDistance"]));
            }
            set {
                this["SnapDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysOnTop {
            get {
                return ((bool)(this["AlwaysOnTop"]));
            }
            set {
                this["AlwaysOnTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double Opacity {
            get {
                return ((double)(this["Opacity"]));
            }
            set {
                this["Opacity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CC0C355B")]
        public global::System.Windows.Media.Color BorderColorTopLeft {
            get {
                return ((global::System.Windows.Media.Color)(this["BorderColorTopLeft"]));
            }
            set {
                this["BorderColorTopLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF104C85")]
        public global::System.Windows.Media.Color BorderColorBottomRight {
            get {
                return ((global::System.Windows.Media.Color)(this["BorderColorBottomRight"]));
            }
            set {
                this["BorderColorBottomRight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4,8,4,4")]
        public global::System.Windows.Thickness BorderThickness {
            get {
                return ((global::System.Windows.Thickness)(this["BorderThickness"]));
            }
            set {
                this["BorderThickness"] = value;
            }
        }
    }
}
