//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Media;

namespace PoshCode.Controls.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Consolas, Lucida Console")]
        public FontFamily FontFamily {
            get {
                return ((FontFamily)(this["FontFamily"]));
            }
            set {
                this["FontFamily"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("12")]
        public double FontSize {
            get {
                return ((double)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool CopyOnMouseSelect {
            get {
                return ((bool)(this["CopyOnMouseSelect"]));
            }
            set {
                this["CopyOnMouseSelect"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("2")]
        public int TabCompleteMenuThreshold {
            get {
                return ((int)(this["TabCompleteMenuThreshold"]));
            }
            set {
                this["TabCompleteMenuThreshold"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("250")]
        public int TabCompleteDoubleTapMilliseconds {
            get {
                return ((int)(this["TabCompleteDoubleTapMilliseconds"]));
            }
            set {
                this["TabCompleteDoubleTapMilliseconds"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool HistoryMenuFilterDupes {
            get {
                return ((bool)(this["HistoryMenuFilterDupes"]));
            }
            set {
                this["HistoryMenuFilterDupes"] = value;
            }
        }
    }
}
